### ISSUE TITLE
Code for core tools and apis should not depend on extensions

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#2305]
### Describe the bug

The point of extensions is to allow anyone to create an extension without modifying core tools or apis.
Currently this is not the case.

- [ ] export_program_info.cpp has knowledge of all program types, including the sample one - Fixed by #3055
- [ ] libs\api_common\windows_program_type.h has knowledge of all program types, including the sample one. - Fixed by #3055
- [ ] #3672
- [ ] sample extension doesn't do what we would want out-of-repo extensions to do. - Fixed by #3055
- [ ] docs\eBpfExtensions.md has no discussion about this.

### Steps taken to reproduce bug

Remove EBPF_PROGRAM_TYPE_SAMPLE from ebpf_program_attach_type_guids.h.
Try to build ebpf for windows.

### Expected behavior

Compilation should succeed.
Thus, adding a new one can be done without loss of functionality.

### Actual outcome

Compilation fails.
Thus, adding a new one cannot be done without loss of functionality.

**Comment by saxena-anurag** [comment]
Regarding `export_program_info` -- it contains all the program and attach types for the ones defined in ebpf repo.
If there is another extension which implements a new program and attach type, it needs to do 2 things:

1. The extension should use the `ebpf store` APIs to populate the registry values.
2. For offline verification, provide a tool similar to `export_program_info` which will populate the same registry keys.

**Comment by dthaler** [comment]
Also `_prog_type_supports_interface()` in libs\ebpfnetsh\programs.cpp  has hard coded knowledge at present, which should not be hard coded.

**Comment by dthaler** [comment]
> Regarding `export_program_info` -- it contains all the program and attach types for the ones defined in ebpf repo. If there is another extension which implements a new program and attach type, it needs to do 2 things:
> 
> 1. The extension should use the `ebpf store` APIs to populate the registry values.
> 2. For offline verification, provide a tool similar to `export_program_info` which will populate the same registry keys.

Sounds fine, but `docs\eBpfExtensions.md` says nothing about that at this point.

**Comment by dv-msft** [comment]
The sub-task ' _prog_type_supports_interface() in libs\ebpfnetsh\programs.cpp has hard coded knowledge at present.' has been forked out into a separate issue (#3671).

**Comment by dv-msft** [comment]
Separate issue #3672 created to track sub-task 3.  All other sub-tasks have been addressed by specific (merged) PRs
