### ISSUE TITLE
Integrate fuzz testing

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#620]
https://github.com/microsoft/onefuzz/blob/main/docs/getting-started.md provides documentation on how to use OneFuzz for fuzz testing

The following surfaces should be fuzz tested:

- [x] ioctls exposed by drivers to user mode components (issue #709)
- [ ] helper functions exposed to ebpf programs (PR #1153)
- [x] rpc apis exposed by the user mode service (PR #1117 tests the verifier directly, since only 1 API is exposed via RPC)

**Comment by dthaler** [comment]
Blocked on #709

**Comment by Alan-Jowett** [comment]
https://github.com/microsoft/onefuzz/issues/1957

Need to better understand how to write a libfuzzer harness.
